[server]
; Servidores relay disponibles — descomenta el que quieras usar:
; relay_addr = 192.241.238.136:11451  ; Servidor 1 — Nueva York, US
; relay_addr = 65.21.20.230:11451     ; Servidor 2 — Helsinki, FI
; relay_addr = 89.163.151.130:11451   ; Servidor 3 — Frankfurt, DE
; relay_addr = 37.187.111.226:11451   ; Servidor 4 — París, FR
; relay_addr = 45.83.241.140:11451    ; Servidor 5 — Ámsterdam, NL
; relay_addr = 185.117.82.250:11451   ; Servidor 6 — Europa
; relay_addr = 37.201.39.187:11451    ; Servidor 7 — Alemania, DE
; relay_addr = 201.83.170.61:11451    ; Servidor 8 — Brasil, BR
; relay_addr = 91.195.240.12:11453    ; Servidor 9 — Europa (puerto 11453)
; relay_addr = 199.60.101.194:11451   ; Servidor 10 — EE.UU., US
relay_addr = 192.241.238.136:11451

; Opcional: fijar IP virtual (por defecto se genera del numero de serie de la consola)
; ip = 10.13.5.10

; Opcional: autenticación si el servidor lo requiere
; username = miusuario
; password = miclave
