[server]
relay_addr = 192.241.238.136:11451

; Opcional: fijar IP virtual (por defecto se genera del numero de serie de la consola)
; ip = 10.13.5.10

; Opcional: autenticación si el servidor lo requiere
; username = miusuario
; password = miclave
